### PR TITLE
Test allinone ci

### PR DESCRIPTION
**Pull request by liusheng**

### CODE REVIEW

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck stable/ocata

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by animationzl** [comment]
recheck stable/ocata

**Comment by animationzl** [comment]
recheck stable/pike

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck stable/newton

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by animationzl** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck stabke/ocata

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by animationzl** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Pull request closed without merging**
