### PR TITLE
Test allinone ci

### PR DESCRIPTION
**Pull request by liusheng**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck stable/newton

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck stable/pike

**Comment by liusheng** [comment]
recheck stable/ocata

**Comment by liusheng** [comment]
recheck stable/ocata

**Pull request closed without merging**
